name: CI

on: [push]

env:
  SCHEME: scheme
  IDRISVERSION: 0.4.0

jobs:
  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: Step 0 - Get Cache
        uses: actions/cache@v2
        id: cache-step
        with:
          path: ~/.idris2
          key: ${{ runner.os }}-build-IDRIS0.4.0
          restore-keys: |
            ${{ runner.os }}-build-IDRIS0.4.0
            ${{ runner.os }}-build
      - name: Step 1 - Install ChezScheme
        run: |
          sudo apt-get update
          sudo apt-get install -y chezscheme
      - name: Step 2 - Install Idris2
        if: steps.cache-step.outputs.cache-hit != 'true'
        id: idris
        run: |
          git clone https://github.com/idris-lang/Idris2
          cd Idris2 
          make bootstrap SCHEME=scheme
          make install
      - name: Step 3 - Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Step 4 - Build Yurei
        run: |
          make install
      - name: Step 5 - Test
        run: |
          make test
